spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ma321388
    url: jdbc:mysql://localhost:3306/springbatch?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
